### ISSUE TITLE
[Feat] 회원 관련 기능 구현

### ISSUE THREAD

**Issue by JHKim9824** [OliviaYJH/TripMate_Server#1]
## ✅ Feat : 회원 관련 기능 구현
> 1. 회원가입
> 2. 이메일 중복 확인
> 3. 로그인

## Description
> Spring Security와 JWT를 적용하여 회원 관련 기능인 회원가입, 이메일 중복 확인, 로그인 기능을 구현

## To-Do

- [x] 회원가입
- [x] 이메일 중복 확인
- [x] 로그인

**Comment by JHKim9824** [comment]
## 회원가입 테스트
![회원가입_테스트](https://github.com/user-attachments/assets/952191a0-844a-4ab0-95af-d7136e298249)

## 로그인 테스트
![로그인_테스트](https://github.com/user-attachments/assets/fada14c4-4d65-4738-94b4-335f1aa4bc7d)


## 이메일 중복확인 테스트
![이메일_중복체크_case1](https://github.com/user-attachments/assets/f0bcb667-c166-4b97-a5e6-2f56c349327f)
![이메일_중복체크_case2](https://github.com/user-attachments/assets/632c3a27-64f0-46d6-8ebd-98bca5539972)

**Comment by JHKim9824** [comment]
## 해결해야하는 이슈

- [x] JwtAuthenticationFilter에서 '어노테이션이 없는 매개변수가 @NonNullApi 매개변수를 재정의합니다' 이슈 해결 필요
- [ ] 애플리케이션 기동 시 User 테이블의 introduce 필드의 지속적인 타입 변경 로그 표출되는 이슈 해결 필요

**Comment by JHKim9824** [comment]
이슈 1번 해결 완료, 2번 추가 조치 필요
