### ISSUE TITLE
[Feat] 실시간 채팅 기능 구현

### ISSUE THREAD

**Issue by Baekchoi** [OliviaYJH/TripMate_Server#21]
## ✅ Feat : 
> 실시간 채팅 기능을 구현합니다.

## Description
> 채팅방은 모임 생성시 자동으로 개설됩니다.
> 모임에 참여한 사용자는 채팅방에 자동으로 참여됩니다.
> 사용자는 채팅방에서 퇴장할 수 있습니다.(모임에서 탈퇴하면 채팅방에서도 퇴장됨)
> 사용자는 다른 사용자들과 메시지를 주고받을 수 있습니다.
> 새로운 메시지가 도착했을 시 알림을 받을 수 있습니다.
> 다른 사용자가 메시지를 읽었는지 확인할 수 있습니다.

## To-Do
- [x] 채팅방 개설, 참여, 퇴장 구현
- [x] 메시지 송수신 구현
- [x] #34
- [ ] 메시지 읽음 여부 구현
