### ISSUE TITLE
[Refactor] 모임 API 코드 수정 및 개선

### ISSUE THREAD

**Issue by Baekchoi** [OliviaYJH/TripMate_Server#35]
## ✅ Refactor : 
> 모임 API 관련 수정 및 개선사항 반영

## Description
> 모임 개설 api 
 - travelStartDate가 현재 날짜 이전인 경우 예외 처리
 - 모임 생성시 meeting entity의 isDeleted 필드 false로 저장
 - 모임 생성시 meeting entity의 updateDate 필드 LocalDate.now로 저장
> 모임 참여 api
 - 모임 참여 시 meeting member entity의 isRemoved 필드 false로 저장
 - 모임 참여 시 meeting member entity의 removeReason 필드 빈문자열로 저장
> 모임 탈퇴 api
 - 모임 탈퇴 시 데이터베이스에서 삭제하지 않고 isRemoved 필드 true로 저장 
## To-Do
- [x] 모임 개설 api 수정 및 개선
- [x] 모임 참여 api 수정 및 개선
- [x] 모임 탈퇴 api 수정 및 개선
